name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: pwsh
        run: |
          py -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install pyinstaller

      - name: Build EXE (onefile)
        shell: pwsh
        run: |
          pyinstaller --noconsole --onefile `
            --name "DawsonDIY-Stock" `
            --hidden-import=barcode `
            --hidden-import=barcode.code128 `
            stock_cost_scanner.py
          # ถ้ามีไอคอน: เพิ่ม --icon assets/app.ico หลัง --name

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DawsonDIY-Stock-win
          path: dist/*
